package clases;

import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

public class EjercicioVerbos {

	public static void main(String[] args) {
		Scanner s = new Scanner (System.in);
		
		ArrayList<Verbo> lista = new ArrayList<Verbo>();
		Random rand = new Random();
		Pistas pista = new Pistas();
		String resultado;
		String resultadoSegundo;
		String resultadoTercero;
		
		Verbo verbo1 = new Verbo("alight","alighted,alit","alighted,alit","apearse,posarse");
		Verbo verbo2 = new Verbo("arise","arose","arisen","surgir,levantarse");
		Verbo verbo3 = new Verbo("awake","awoke,awaked","awoken,awaked","despertar");
		Verbo verbo4 = new Verbo("be","was,were","been","ser");
		Verbo verbo5 = new Verbo("bear","bore","borne,born","soportar,cargar");
		Verbo verbo6 = new Verbo("beat","beat","beaten,beat","golpear,vencer");
		Verbo verbo7 = new Verbo("become","became","become","volverse,convertirse");
		Verbo verbo8 = new Verbo("beget","begot","begotten","provocar,engendrar");
		Verbo verbo9 = new Verbo("begin","began","begun","empezar,comenzar");
		Verbo verbo10 = new Verbo("bend","bent","bent","torcer,doblar");
		Verbo verbo11= new Verbo("bereave","bereaved,bereft","bereaved,bereft","despojar");
		Verbo verbo12 = new Verbo("beseech","besought,beseeched","besought,beseeched","suplicar,rogar");
		Verbo verbo13 = new Verbo("bet","bet,betted","bet,betted","apostar");
		Verbo verbo14 = new Verbo("bid","bid","bid","ofrecer");
		Verbo verbo15 = new Verbo("bide","bade,bided","bided","esperar,aguardar");
		Verbo verbo16 = new Verbo("bind","bound","bound","atar, amarrar, unir");
		Verbo verbo17 = new Verbo("bite","bit",	"bitten","morder");
		Verbo verbo18 = new Verbo("bleed","bled","bled","sangrar");
		Verbo verbo19 = new Verbo("bless","blessed,blest","blessed,blest","bendecir");
		Verbo verbo20 = new Verbo("blow","blew","blown","soplar");
		Verbo verbo21 = new Verbo("break","broke","broken","romper");
		Verbo verbo22 = new Verbo("breed","bred","bred","criar");
		Verbo verbo23 = new Verbo("bring","brought","brought","traer");
		Verbo verbo24 = new Verbo("broadcast","broadcast","broadcast","transmitir");
		Verbo verbo25 = new Verbo("build","built","built","construir");
		Verbo verbo26 = new Verbo("burn","burnt,burned","burnt,burned","quemar");
		Verbo verbo27 = new Verbo("burst","burst","burst","reventar,desbordarse");
		Verbo verbo28 = new Verbo("bust","busted","bust,busted","atrapar");
		Verbo verbo29 = new Verbo("buy","bought","bought","comprar");
		Verbo verbo30 = new Verbo("can","could","(sin participio)","poder");
		Verbo verbo31 = new Verbo("cast","cast","cast","lanzar,tirar,echar");
		Verbo verbo32 = new Verbo("catch","caught","caught","coger");
		Verbo verbo33 = new Verbo("choose","chose",	"chosen","elegir");
		Verbo verbo34 = new Verbo("cleave","cleft,cleaved,clove","cleft,cleaved,cloven","partir,hender");
		Verbo verbo35 = new Verbo("cling","clung","clung","aferrarse");
		Verbo verbo36 = new Verbo("clothe","clothed,clad","clothed,clad","vestir");
		Verbo verbo37 = new Verbo("come","came","come","venir");
		Verbo verbo38 = new Verbo("cost","cost","cost","costar");
		Verbo verbo39 = new Verbo("creep","crept","crept","arrastrarse");
		Verbo verbo40 = new Verbo("crow","crowed","crew,crowed","cacarear,alardear");
		Verbo verbo41 = new Verbo("cut","cut","cut","cortar");
		Verbo verbo42 = new Verbo("deal","dealt","dealt","repartir,dar");
		Verbo verbo43 = new Verbo("dig","dug","dug","cavar");
		Verbo verbo44 = new Verbo("do","did","done","hacer");
		Verbo verbo45 = new Verbo("draw","drew","drawn","dibujar");
		Verbo verbo46 = new Verbo("dream","dreamt,dreamed","dreamt,dreamed","soñar");
		Verbo verbo47 = new Verbo("drink","drank","drunk","beber");
		Verbo verbo48 = new Verbo("drive","drove","driven","conducir");
		Verbo verbo49 = new Verbo("dwell","dwelt,dwelled","dwelt,dwelled","morar,vivir");
		Verbo verbo50 = new Verbo("eat","ate","eaten","comer");
		Verbo verbo51 = new Verbo("fall","fell","fallen","caer, caerse");
		Verbo verbo52 = new Verbo("feed","fed","fed","alimentar");
		Verbo verbo53 = new Verbo("feel","felt","felt","sentir");
		Verbo verbo54 = new Verbo("fight","fought","fought","luchar");
		Verbo verbo55 = new Verbo("find","found","found","encontrar");
		Verbo verbo56 = new Verbo("flee","fled","fled","huir, escapar");
		Verbo verbo57 = new Verbo("fling","flung","flung","lanzar, arrojar");
		Verbo verbo58 = new Verbo("fly","flew","flown","volar");
		Verbo verbo59 = new Verbo("forbid","forbad,forbade","forbid,forbidden","prohibir");
		Verbo verbo60 = new Verbo("forecast","forecast,forecasted","forecast,forecasted","predecir");
		Verbo verbo61 = new Verbo("forget","forgot","forgotten","olvidar");
		Verbo verbo62 = new Verbo("forsake","forsook","forsaken","abandonar,renunciar");
		Verbo verbo63 = new Verbo("freeze","froze","frozen","congelar");
		Verbo verbo64 = new Verbo("geld","gelded,gelt","gelded,gelt","castrar");
		Verbo verbo65 = new Verbo("get","got","got,gotten","conseguir");
		Verbo verbo66 = new Verbo("gild","gilded,gilt","gilded,gilt","dorar");
		Verbo verbo67 = new Verbo("give","gave","given","dar");
		Verbo verbo68 = new Verbo("gnaw","gnawed","gnawed,gnawn","roer");
		Verbo verbo69 = new Verbo("go","went","gone","ir");
		Verbo verbo70 = new Verbo("grind","ground","ground","moler");
		Verbo verbo71 = new Verbo("grip","gripped,gript","gripped,gript","agarrar");
		Verbo verbo72 = new Verbo("grow","grew","grown","crecer");
		Verbo verbo73 = new Verbo("hang","hung","hung","colgar");
		Verbo verbo74 = new Verbo("have","had","had","tener");
		Verbo verbo75 = new Verbo("hear","heard","heard","oír");
		Verbo verbo76 = new Verbo("heave","heaved,hove","heaved,hove","tirar, estirar");
		Verbo verbo77 = new Verbo("hew","hewed","hewed,hewn","labrar,tallar");
		Verbo verbo78 = new Verbo("hide","hid","hidden,hid","esconder(se)");
		Verbo verbo79 = new Verbo("hit","hit","hit","golpear");
		Verbo verbo80 = new Verbo("hold","held","held","tener");
		Verbo verbo81 = new Verbo("hurt","hurt","hurt","herir, hacer daño");
		Verbo verbo82 = new Verbo("keep","kept","kept","guardar, conservar");
		Verbo verbo83 = new Verbo("kneel","knelt, kneeled",	"knelt, kneeled","arrodillar(se)");
		Verbo verbo84 = new Verbo("knit","knitted, knit	","knitted, knit	","tejer");
		Verbo verbo85 = new Verbo("know","knew","known","saber");
		Verbo verbo86 = new Verbo("lay","laid","laid","poner, extender");
		Verbo verbo87 = new Verbo("lead","led","led","guiar");
		Verbo verbo88 = new Verbo("lean","leant,leaned","leant,leaned","inclinarse");
		Verbo verbo89 = new Verbo("leap","leapt,leaped","leapt,leaped","saltar");
		Verbo verbo90 = new Verbo("learn","learnt, learned","learnt, learned","aprender");
		Verbo verbo91 = new Verbo("leave","left","left","salir,irse,abandonar");
		Verbo verbo92 = new Verbo("lend","lent","lent","prestar,dejar");
		Verbo verbo93 = new Verbo("let","let","let","dejar");
		Verbo verbo94 = new Verbo("lie","lay","lain","mentir");
		Verbo verbo95 = new Verbo("light","lit","lit","encender");
		Verbo verbo96 = new Verbo("lose","lost","lost","perder");
		Verbo verbo97 = new Verbo("make","made","made","hacer");
		Verbo verbo98 = new Verbo("may","might","(sin participio)","poder");
		Verbo verbo99 = new Verbo("mean","meant","meant","significar");
		Verbo verbo100 = new Verbo("meet","met","met","conocer");
		Verbo verbo101 = new Verbo("melt","melted","molten, melted","derretir");
		Verbo verbo102 = new Verbo("mow","mowed","mown, mowed","segar");
		Verbo verbo103 = new Verbo("pay","paid","paid","pagar");
		Verbo verbo104 = new Verbo("pen","pent,penned","pent, penne","escribir, redactar");
		Verbo verbo105 = new Verbo("plead","pled, pleaded","pled,pleaded","alegar");
		Verbo verbo106 = new Verbo("prove","proved","proven,proved","probar");
		Verbo verbo107 = new Verbo("put","put","put","poner");
		Verbo verbo108 = new Verbo("quit","quit,quitted","quit,quitted","abandonar");
		Verbo verbo109 = new Verbo("read","read","read","leer");
		Verbo verbo110 = new Verbo("rid	","rid,ridded","rid,ridded","deshacerse de");
		Verbo verbo111 = new Verbo("ride","rode","ridden","montar (a caballo, en bici…)");
		Verbo verbo112 = new Verbo("ring","rang","rung","sonar,repicar,telefonear");
		Verbo verbo113 = new Verbo("rise","rose","risen","subir,levantarse");
		Verbo verbo114 = new Verbo("run","ran","run","correr");
		Verbo verbo115 = new Verbo("saw","sawed","sawn,sawed","serrar");
		Verbo verbo116 = new Verbo("say","said","said","decir");
		Verbo verbo117 = new Verbo("see","saw","seen","ver");
		Verbo verbo118 = new Verbo("seek","sought","sought","buscar");
		Verbo verbo119 = new Verbo("sell","sold","sold","vender");
		Verbo verbo120 = new Verbo("send","sent","sent","enviar");
		Verbo verbo121 = new Verbo("set","set","set","poner, colocar");
		Verbo verbo122 = new Verbo("sew","sewed	","sewn,sewed","coser");
		Verbo verbo123 = new Verbo("shake","shook","shaken","agitar");
		Verbo verbo124 = new Verbo("shall","should","(sin participio)","deber");
		Verbo verbo125 = new Verbo("shear","sheared","shorn,sheared","esquilar");
		Verbo verbo126 = new Verbo("shed","shed","shed","derramar,liberarse");
		Verbo verbo127 = new Verbo("shine","shone","shone","brillar");
		Verbo verbo128 = new Verbo("shit","shit,shitted,shat","shit,shitted,shat","cagar");
		Verbo verbo129 = new Verbo("shoe","shod,shoed","shod,shoed","herrar");
		Verbo verbo130 = new Verbo("shoot","shot","shot","tirar,rodar(película)");
		Verbo verbo131 = new Verbo("show","showed","shown,showed","mostrar");
		Verbo verbo132 = new Verbo("shred","shred,shredded","shred,shredded","destruir,cortar");
		Verbo verbo133 = new Verbo("shrink","shrank,shrunk","shrunk","encoger");
		Verbo verbo134 = new Verbo("shut","shut","shut","cerrar");
		Verbo verbo135 = new Verbo("sing","sang","sung","cantar");
		Verbo verbo136 = new Verbo("sink","sank","sunk","hundir");
		Verbo verbo137 = new Verbo("sit","sat","sat","sentar");
		Verbo verbo138 = new Verbo("slay","slew","slain","asesinar");
		Verbo verbo139 = new Verbo("sleep","slept","slept","dormir");
		Verbo verbo140 = new Verbo("slide","slid","slid","deslizarse");
		Verbo verbo141 = new Verbo("sling","slung","slung","tirar,lanzar");
		Verbo verbo142 = new Verbo("slink","slunk","slunk","escaparse,andar a hurtadillas");
		Verbo verbo143 = new Verbo("slit","slit","slit","cortar,rajar");
		Verbo verbo144 = new Verbo("smell","smelt,smelled","smelt, smelled","oler");
		Verbo verbo145 = new Verbo("smite","smote","smitten","golpear");
		Verbo verbo146 = new Verbo("sow	","sowed","sown,sowed","sembrar");
		Verbo verbo147 = new Verbo("speak","spoke","spoken","hablar");
		Verbo verbo148 = new Verbo("speed","sped,speeded","sped,speeded","acelerar");
		Verbo verbo149 = new Verbo("spell","spelt,spelled","spelt, spelled","deletrear, escribir");
		Verbo verbo150 = new Verbo("spend","spent","spent","gastar");
		Verbo verbo151 = new Verbo("spill","spilt,spilled","spilt, spilled","derramar");
		Verbo verbo152 = new Verbo("spin","spun","spun","girar");
		Verbo verbo153 = new Verbo("spit","spat","spat","escupir");
		Verbo verbo154 = new Verbo("split","split","split","partir,dividir");
		Verbo verbo155 = new Verbo("spoil","spoilt,","spoiled,spoilt,spoiled","estropear");
		Verbo verbo156 = new Verbo("spread","spread","spread","extender");
		Verbo verbo157 = new Verbo("spring","sprang,sprung","sprung","saltar");
		Verbo verbo158 = new Verbo("stand","stood","stood","estar de pie");
		Verbo verbo159 = new Verbo("steal","stole","stolen","robar");
		Verbo verbo160 = new Verbo("stick","stuck","stuck","pegar");
		Verbo verbo161 = new Verbo("sting","stung","stung","picar");
		Verbo verbo162 = new Verbo("stink","stank,stunk","stunk","apestar");
		Verbo verbo163 = new Verbo("stride","strode","stridden","dar zancadas");
		Verbo verbo164 = new Verbo("strike","struck","struck","golpear");
		Verbo verbo165 = new Verbo("string","strung","strung","colgar");
		Verbo verbo166 = new Verbo("strive","strove","striven","luchar,esforzarse");
		Verbo verbo167 = new Verbo("swear","swore","sworn","jurar");
		Verbo verbo168 = new Verbo("sweat","sweat,sweated","sweat,sweated","sudar");
		Verbo verbo169 = new Verbo("sweep","swept","swept","barrer");
		Verbo verbo170 = new Verbo("swell","swelled","swollen,swelled","hincharse");
		Verbo verbo171 = new Verbo("swim","swam","swum","nadar");
		Verbo verbo172 = new Verbo("swing","swung","swung","balancearse");
		Verbo verbo173 = new Verbo("take","took","taken","coger");
		Verbo verbo174 = new Verbo("teach","taught","taught","enseñar");
		Verbo verbo175 = new Verbo("tear","tore","torn","rasgar");
		Verbo verbo176 = new Verbo("telecast","telecast,telecasted","telecast,telecasted","televisar");
		Verbo verbo177 = new Verbo("tell","told","told","decir,contar");
		Verbo verbo178 = new Verbo("think","thought","thought","pensar");
		Verbo verbo179 = new Verbo("throw","threw","thrown","tirar,lanzar");
		Verbo verbo180 = new Verbo("thrust","thrust","thrust","sacar,clavar");
		Verbo verbo181 = new Verbo("tread","trod","trodden","pisar");
		Verbo verbo182 = new Verbo("understand","understood","understood","entender");
		Verbo verbo183 = new Verbo("wake","woke, waked","woken, waked","despertar");
		Verbo verbo184 = new Verbo("wear","wore","worn","llevar");
		Verbo verbo185 = new Verbo("weave","wove","woven","tejer");
		Verbo verbo186 = new Verbo("wed","wed, wedded","wed,wedded","esposar,casarse con");
		Verbo verbo187 = new Verbo("weep","wept","wept","llorar");
		Verbo verbo188 = new Verbo("wet","wet,wetted","wet,wetted","mojar,humedecer");
		Verbo verbo189 = new Verbo("win","won",	"won","ganar");
		Verbo verbo190 = new Verbo("wind","wound","wound","dejar sin aliento");
		Verbo verbo191 = new Verbo("wring","wrung","wrung","estrujar");
		Verbo verbo192 = new Verbo("write","wrote","written","escribir");
		
		
		lista.add(verbo1);
		lista.add(verbo2);
		lista.add(verbo3);
		lista.add(verbo4);
		lista.add(verbo5);
		lista.add(verbo6);
		lista.add(verbo7);
		lista.add(verbo8);
		lista.add(verbo9);
		lista.add(verbo10);
		lista.add(verbo11);
		lista.add(verbo12);
		lista.add(verbo13);
		lista.add(verbo14);
		lista.add(verbo15);
		lista.add(verbo16);
		lista.add(verbo17);
		lista.add(verbo18);
		lista.add(verbo19);
		lista.add(verbo20);
		lista.add(verbo21);
		lista.add(verbo22);
		lista.add(verbo23);
		lista.add(verbo24);
		lista.add(verbo25);
		lista.add(verbo26);
		lista.add(verbo27);
		lista.add(verbo28);
		lista.add(verbo29);
		lista.add(verbo30);
		lista.add(verbo31);
		lista.add(verbo32);
		lista.add(verbo33);
		lista.add(verbo34);
		lista.add(verbo35);
		lista.add(verbo36);
		lista.add(verbo37);
		lista.add(verbo38);
		lista.add(verbo39);
		lista.add(verbo40);
		lista.add(verbo41);
		lista.add(verbo42);
		lista.add(verbo43);
		lista.add(verbo44);
		lista.add(verbo45);
		lista.add(verbo46);
		lista.add(verbo47);
		lista.add(verbo48);
		lista.add(verbo49);
		lista.add(verbo50);
		lista.add(verbo51);
		lista.add(verbo52);
		lista.add(verbo53);
		lista.add(verbo54);
		lista.add(verbo55);
		lista.add(verbo56);
		lista.add(verbo57);
		lista.add(verbo58);
		lista.add(verbo59);
		lista.add(verbo60);
		lista.add(verbo61);
		lista.add(verbo62);
		lista.add(verbo63);
		lista.add(verbo64);
		lista.add(verbo65);
		lista.add(verbo66);
		lista.add(verbo67);
		lista.add(verbo68);
		lista.add(verbo69);
		lista.add(verbo70);
		lista.add(verbo71);
		lista.add(verbo72);
		lista.add(verbo73);
		lista.add(verbo74);
		lista.add(verbo75);
		lista.add(verbo76);
		lista.add(verbo77);
		lista.add(verbo78);
		lista.add(verbo79);
		lista.add(verbo80);
		lista.add(verbo81);
		lista.add(verbo82);
		lista.add(verbo83);
		lista.add(verbo84);
		lista.add(verbo85);
		lista.add(verbo86);
		lista.add(verbo87);
		lista.add(verbo88);
		lista.add(verbo89);
		lista.add(verbo90);
		lista.add(verbo91);
		lista.add(verbo92);
		lista.add(verbo93);
		lista.add(verbo94);
		lista.add(verbo95);
		lista.add(verbo96);
		lista.add(verbo97);
		lista.add(verbo98);
		lista.add(verbo99);
		lista.add(verbo100);
		lista.add(verbo101);
		lista.add(verbo102);
		lista.add(verbo103);
		lista.add(verbo104);
		lista.add(verbo105);
		lista.add(verbo106);
		lista.add(verbo107);
		lista.add(verbo108);
		lista.add(verbo109);
		lista.add(verbo110);
		lista.add(verbo111);
		lista.add(verbo112);
		lista.add(verbo113);
		lista.add(verbo114);
		lista.add(verbo115);
		lista.add(verbo116);
		lista.add(verbo117);
		lista.add(verbo118);
		lista.add(verbo119);
		lista.add(verbo120);
		lista.add(verbo121);
		lista.add(verbo122);
		lista.add(verbo123);
		lista.add(verbo124);
		lista.add(verbo125);
		lista.add(verbo126);
		lista.add(verbo127);
		lista.add(verbo128);
		lista.add(verbo129);
		lista.add(verbo130);
		lista.add(verbo131);
		lista.add(verbo132);
		lista.add(verbo133);
		lista.add(verbo134);
		lista.add(verbo135);
		lista.add(verbo136);
		lista.add(verbo137);
		lista.add(verbo138);
		lista.add(verbo139);
		lista.add(verbo140);
		lista.add(verbo141);
		lista.add(verbo142);
		lista.add(verbo143);
		lista.add(verbo144);
		lista.add(verbo145);
		lista.add(verbo146);
		lista.add(verbo147);
		lista.add(verbo148);
		lista.add(verbo149);
		lista.add(verbo150);
		lista.add(verbo151);
		lista.add(verbo152);
		lista.add(verbo153);
		lista.add(verbo154);
		lista.add(verbo155);
		lista.add(verbo156);
		lista.add(verbo157);
		lista.add(verbo158);
		lista.add(verbo159);
		lista.add(verbo160);
		lista.add(verbo161);
		lista.add(verbo162);
		lista.add(verbo163);
		lista.add(verbo164);
		lista.add(verbo165);
		lista.add(verbo166);
		lista.add(verbo167);
		lista.add(verbo168);
		lista.add(verbo169);
		lista.add(verbo170);
		lista.add(verbo171);
		lista.add(verbo172);
		lista.add(verbo173);
		lista.add(verbo174);
		lista.add(verbo175);
		lista.add(verbo176);
		lista.add(verbo177);
		lista.add(verbo178);
		lista.add(verbo179);
		lista.add(verbo180);
		lista.add(verbo181);
		lista.add(verbo182);
		lista.add(verbo183);
		lista.add(verbo184);
		lista.add(verbo185);
		lista.add(verbo186);
		lista.add(verbo187);
		lista.add(verbo188);
		lista.add(verbo189);
		lista.add(verbo190);
		lista.add(verbo191);
		lista.add(verbo192);
		
		pista.agregarPista("spread","I spread my lands five kilometers ");
		
		System.out.println("Ejercicio para los verbos irregulares");

		int marcador = 0;
		int marcadorFinal = 0;
		
		while(marcador >= 0) {
			// Seleccionar una palabra aleatoria de la lista
			Verbo palabraAleatoria = lista.get(rand.nextInt(lista.size()));
			
			System.out.print("Significado "+palabraAleatoria.getInfinitivo()+" --> ");
			resultado = s.next();
			if(resultado.equalsIgnoreCase(palabraAleatoria.getSignificado())) {
				marcador++;
				System.out.print("Pasado --> ");
				resultadoSegundo = s.next();
				if(resultadoSegundo.equalsIgnoreCase(palabraAleatoria.getPasado())) {
					marcador++;
					System.out.print("Participio --> ");
					resultadoTercero = s.next();
					if(resultadoTercero.equalsIgnoreCase(palabraAleatoria.getParticipio())){
						marcadorFinal++;
						System.out.println("");
					}
					else {
						System.out.println("Error, la palabra correcta es: "+palabraAleatoria.getParticipio());
						System.out.println("Tu marcador es: "+marcadorFinal);
						marcador = -1;
					}
					
				}
				else {
					System.out.println("Error, la palabra correcta es: "+palabraAleatoria.getPasado());
					System.out.println("Tu marcador es: "+marcadorFinal);
					marcador = -1;
				}
			}
			else {
				System.out.println("Error, la palabra correcta es: "+palabraAleatoria.getSignificado());
				System.out.println("Tu marcador es: "+marcadorFinal);
				marcador = -1;
			}
		}
		
		s.close();
	}
}